import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from "@/components/ui/sonner";

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thread Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en" className={`${raleway.variable} dark`}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <div className="flex min-h-screen flex-col bg-background text-foreground">
                <main className="flex flex-1 flex-col">
                    <div className="mx-auto flex w-full max-w-6xl  flex-1 flex-col px-4 py-8 md:py-10">
                        {children}
                    </div>
                </main>
            </div>
            <Toaster/>
            </body>
        </html>
      </ClerkProvider>
  );
}
